-- MySQL Script generated by MySQL Workbench
-- Sun Nov 30 23:54:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotelaria
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estreladoaraguaia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estreladoaraguaia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estreladoaraguaia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `estreladoaraguaia` ;

-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`clientes` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`quartos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`quartos` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`quartos` (
  `id_quarto` INT NOT NULL AUTO_INCREMENT,
  `numero_quarto` INT NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `capacidade_maxima` INT NOT NULL,
  `valor_diaria_base` DECIMAL(10,2) NOT NULL,
  `status_quarto` ENUM('Disponível', 'Reservado', 'Ocupado', 'Manutenção') NULL DEFAULT 'Disponível',
  PRIMARY KEY (`id_quarto`),
  UNIQUE INDEX `numero_quarto` (`numero_quarto` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`reservas` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_quarto` INT NOT NULL,
  `data_checkin_prevista` DATE NOT NULL,
  `data_checkout_prevista` DATE NOT NULL,
  `valor_total_previsto` DECIMAL(10,2) NULL DEFAULT NULL,
  `status_reserva` ENUM('Confirmada', 'Pendente', 'Cancelada') NULL DEFAULT 'Pendente',
  `id_cliente` INT NOT NULL,
  `id_quarto` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_quarto` (`id_quarto` ASC) VISIBLE,
  INDEX `fk_reservas_clientes_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_reservas_quartos1_idx` (`id_quarto` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`hospedagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`hospedagens` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`hospedagens` (
  `id_hospedagem` INT NOT NULL AUTO_INCREMENT,
  `data_hora_checkin` DATETIME NOT NULL,
  `data_hora_checkout` DATETIME NULL DEFAULT NULL,
  `qtd_hospedes` INT NOT NULL,
  `valor_total_final` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_cliente` INT NOT NULL,
  `id_quarto` INT NOT NULL,
  `id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_hospedagem`),
  INDEX `fk_hospedagens_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_hospedagens_quartos1_idx` (`id_quarto` ASC) VISIBLE,
  INDEX `fk_hospedagens_reservas1_idx` (`id_reserva` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`servicos` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`servicos` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `estreladoaraguaia`.`consumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estreladoaraguaia`.`consumo` ;

CREATE TABLE IF NOT EXISTS `estreladoaraguaia`.`consumo` (
  `id_consumo` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL DEFAULT '1',
  `data_hora_consumo` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_hospedagem` INT NOT NULL,
  `id_servico` INT NOT NULL,
  PRIMARY KEY (`id_consumo`),
  INDEX `fk_consumo_hospedagens1_idx` (`id_hospedagem` ASC) VISIBLE,
  INDEX `fk_consumo_servicos1_idx` (`id_servico` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
