INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 542', 2425.44, 131, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 401', 3411.91, 80, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 795', 3582.89, 222, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 637', 2416.3, 295, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 510', 4706.84, 272, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 640', 716.61, 245, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 171', 2378.98, 1, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 399', 2310.36, 204, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 374', 2271.69, 80, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 258', 1060.21, 180, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 853', 4697.97, 187, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 943', 1672.91, 125, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 458', 2521.81, 167, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 407', 2850.83, 95, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 841', 3075.47, 134, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 644', 3954.79, 279, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 671', 3719.39, 266, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 730', 4542.5, 249, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 467', 226.45, 131, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 823', 482.32, 149, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 445', 332.98, 31, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 135', 3967.84, 76, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 919', 2620.88, 115, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 855', 1768.59, 110, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 619', 4684.47, 273, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 157', 4549.07, 78, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 215', 3945.86, 93, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 607', 4116.59, 230, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 559', 1562.91, 122, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 953', 3232.52, 16, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 276', 2465.6, 48, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 546', 4820.05, 51, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 752', 565.25, 248, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 883', 337.92, 3, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 468', 3548.75, 287, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 817', 4714.2, 249, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 842', 2856.87, 23, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 759', 845.85, 258, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 740', 2578.14, 244, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 731', 4025.46, 114, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 593', 2122.6, 282, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 142', 912.38, 111, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 630', 3011.14, 194, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 606', 3581.26, 83, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 542', 4236.94, 97, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 791', 4215.05, 198, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 966', 3757.19, 127, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 361', 3234.65, 101, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 499', 3842.27, 86, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 673', 3990.11, 82, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 165', 1267.4, 39, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 374', 4476.6, 214, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 576', 1787.45, 199, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 422', 1504.65, 85, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 602', 3669.44, 210, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 296', 3979.08, 70, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 287', 1089.44, 222, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 621', 4829.7, 111, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 721', 1142.4, 83, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 584', 2364.67, 134, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 520', 3822.08, 172, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 337', 3321.26, 70, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 190', 4601.04, 154, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 529', 2657.91, 85, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 873', 2802.07, 294, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 462', 4634.69, 100, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 101', 464.25, 136, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 629', 3892.73, 170, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 126', 2416.51, 155, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 217', 2700.74, 190, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 443', 1369.07, 225, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 705', 4682.28, 124, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 493', 232.38, 258, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 617', 1207.65, 223, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 931', 4635.07, 238, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 791', 870.63, 139, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 230', 574.87, 60, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 390', 3350.68, 10, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 729', 2141.93, 10, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 749', 4154.19, 293, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 854', 89.27, 183, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 233', 3273.72, 263, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 166', 1394.15, 74, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 400', 1219.2, 70, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 827', 4511.71, 24, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 936', 3198.07, 275, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 923', 2831.8, 114, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 290', 3163.01, 185, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 672', 654.9, 235, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 338', 3471.72, 14, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 512', 3329.23, 174, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 828', 771.32, 150, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 721', 577.07, 155, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 220', 613.83, 221, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 753', 1987.39, 135, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 770', 1600.61, 293, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 430', 2351.0, 189, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 545', 1714.62, 115, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 735', 3179.9, 110, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 962', 1639.96, 26, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 918', 3100.43, 151, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 912', 2306.75, 153, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 804', 2009.34, 186, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 780', 3855.74, 257, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 957', 3436.26, 174, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 202', 3277.13, 125, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 916', 3224.65, 271, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 905', 1751.18, 129, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 432', 1867.56, 157, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 333', 3525.1, 257, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 483', 595.12, 201, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 291', 4795.29, 181, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 771', 4775.86, 265, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 590', 389.17, 122, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 890', 87.83, 192, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 143', 3837.13, 15, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 247', 3226.38, 172, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 632', 4748.84, 291, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 247', 1879.98, 220, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 928', 3533.71, 194, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 283', 4550.27, 286, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 837', 981.32, 260, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 483', 315.31, 14, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 718', 793.6, 238, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 669', 2692.36, 37, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 664', 2041.36, 235, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 794', 2973.77, 251, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 392', 2393.33, 265, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 664', 3566.23, 242, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 237', 595.91, 271, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 210', 2819.63, 145, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 324', 3343.73, 178, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 390', 1680.36, 191, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 854', 3925.48, 107, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 183', 59.91, 101, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 910', 1110.38, 74, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 772', 2430.39, 79, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 360', 767.42, 130, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 895', 4322.12, 25, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 464', 3893.68, 61, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 979', 1195.87, 53, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 765', 3260.21, 159, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 560', 233.01, 144, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 782', 1965.7, 88, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 359', 561.35, 207, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 765', 1650.05, 160, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 527', 943.29, 46, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 702', 3961.63, 296, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 283', 4899.25, 273, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 253', 2755.82, 109, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 142', 3983.77, 41, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 849', 1314.21, 268, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 320', 2914.45, 177, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 981', 1900.74, 90, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 639', 2112.11, 33, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 804', 4429.75, 85, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 292', 427.53, 173, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 482', 514.08, 97, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 847', 2511.55, 178, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 267', 764.7, 10, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 393', 400.7, 114, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 640', 510.36, 138, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 196', 3354.79, 189, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 892', 2868.06, 18, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 924', 4967.18, 217, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 489', 4279.04, 102, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 590', 3075.07, 245, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 535', 4212.09, 100, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 924', 1065.9, 154, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 486', 4866.08, 184, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 886', 251.58, 256, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 134', 4792.85, 174, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 876', 3301.24, 126, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 212', 2296.87, 212, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 769', 2530.54, 76, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 285', 1772.78, 116, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 638', 2377.43, 30, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 313', 740.01, 46, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 147', 2313.92, 21, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 746', 909.02, 299, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 923', 2077.51, 15, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 307', 284.96, 253, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 762', 4255.95, 184, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 694', 3641.05, 273, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 970', 1725.07, 58, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 766', 646.18, 52, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 213', 3085.54, 56, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 846', 578.46, 86, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 650', 1472.79, 129, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 432', 4239.48, 48, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 814', 2277.96, 1, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 415', 2039.23, 279, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 130', 4093.9, 55, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 300', 4107.19, 204, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 213', 4812.03, 52, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 110', 1468.02, 5, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 596', 1867.14, 217, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 520', 3488.93, 188, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 645', 2001.07, 269, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 705', 419.04, 238, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 200', 1013.13, 85, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 868', 4334.13, 28, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 822', 286.16, 130, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 737', 1666.65, 254, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 506', 1099.58, 213, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 605', 4877.16, 158, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 809', 653.86, 185, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 787', 502.35, 146, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 189', 1138.44, 21, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 450', 2393.21, 11, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 558', 3121.33, 291, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 539', 918.34, 265, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 234', 3600.94, 207, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 290', 3532.07, 136, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 812', 4045.69, 141, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 107', 2860.5, 54, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 742', 4261.54, 108, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 880', 4392.21, 26, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 985', 4831.92, 82, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 305', 1981.25, 134, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 591', 3422.8, 171, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 219', 3285.69, 237, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 440', 3101.64, 130, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 779', 742.87, 86, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 357', 4471.55, 293, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 576', 1009.09, 19, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 433', 3300.42, 101, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 208', 3421.92, 236, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 134', 2687.5, 23, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 997', 4982.38, 86, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 284', 1430.92, 150, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 530', 1784.28, 238, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 612', 1877.17, 108, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 361', 3365.5, 82, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 882', 4950.58, 30, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 752', 3637.43, 201, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 369', 4712.04, 124, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 445', 3323.26, 7, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 557', 3699.75, 82, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 561', 1380.71, 201, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 935', 1050.33, 262, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 928', 2238.93, 147, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 516', 1757.46, 166, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 567', 4355.59, 261, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 844', 2040.85, 261, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 425', 1363.41, 123, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 284', 2519.84, 269, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 649', 1308.66, 265, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 305', 56.64, 214, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 365', 4482.77, 181, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 131', 1098.01, 40, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 799', 4451.42, 251, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 965', 1521.71, 252, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 538', 450.06, 209, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 684', 3803.92, 126, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 847', 209.37, 50, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 109', 487.06, 152, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 376', 3334.75, 280, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 439', 4845.21, 197, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 275', 2272.45, 70, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 986', 323.71, 257, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 809', 3488.42, 250, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 967', 1896.85, 263, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 795', 1233.31, 224, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 214', 1955.85, 181, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 792', 2783.35, 291, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 540', 1836.19, 198, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 174', 2076.76, 206, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 632', 1105.16, 184, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 960', 275.09, 39, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 893', 803.04, 120, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 701', 2467.37, 138, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 640', 1510.23, 134, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 293', 4231.19, 289, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 834', 1444.41, 264, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 927', 2888.54, 295, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 265', 122.49, 80, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 339', 1162.61, 273, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 224', 4332.11, 261, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 115', 2333.0, 63, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 884', 3894.67, 202, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 153', 3961.79, 148, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 389', 294.75, 156, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 340', 2253.2, 292, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 342', 943.8, 133, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 942', 3049.47, 22, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 137', 2203.33, 206, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 553', 2556.69, 44, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 767', 1896.85, 110, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 682', 586.09, 156, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 955', 2128.43, 281, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 502', 4121.61, 279, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 435', 4848.51, 88, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 544', 1269.41, 205, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 243', 1107.66, 16, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 348', 3301.85, 61, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 732', 4901.19, 135, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 588', 3326.82, 64, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 395', 277.49, 234, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 728', 3899.99, 206, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 854', 247.68, 138, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 971', 3393.75, 209, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 813', 1934.17, 150, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 203', 4987.18, 290, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 544', 2632.77, 108, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 579', 3585.38, 28, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 740', 3357.75, 223, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 203', 3459.81, 139, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 308', 70.66, 252, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 116', 1673.78, 170, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 319', 4025.92, 277, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 908', 2451.98, 29, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 336', 2864.29, 6, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 924', 3639.39, 265, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 681', 3893.13, 223, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 148', 4290.65, 180, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 497', 1896.99, 35, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 750', 3313.46, 278, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 104', 3344.18, 31, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 404', 4134.56, 116, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 361', 4517.74, 244, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 135', 619.79, 130, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 794', 1142.0, 28, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 344', 3577.58, 224, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 795', 2784.71, 79, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 763', 2950.42, 34, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 502', 1430.93, 45, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 973', 3741.43, 159, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 986', 4055.51, 52, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 766', 1786.23, 181, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 874', 2729.53, 279, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 847', 3299.72, 176, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 581', 130.12, 208, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 406', 2630.27, 196, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 846', 1818.35, 294, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 148', 4176.74, 173, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 150', 420.59, 242, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 591', 4673.35, 128, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 477', 4265.39, 58, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 587', 2008.59, 298, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 177', 4654.02, 203, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 259', 3951.02, 51, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 512', 4388.76, 162, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 626', 3193.72, 98, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 979', 4591.22, 251, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 164', 1827.82, 13, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 134', 1951.15, 78, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 686', 1887.93, 185, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 318', 178.3, 233, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 609', 1987.68, 117, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 794', 1636.2, 212, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 194', 3696.57, 80, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 386', 4114.56, 40, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 940', 1054.71, 238, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 814', 2461.91, 137, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 134', 3712.45, 255, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 928', 2305.48, 45, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 873', 4391.57, 207, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 741', 1105.34, 86, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 636', 3918.33, 181, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 260', 953.46, 62, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 101', 2903.8, 31, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 462', 502.54, 28, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 646', 3185.04, 139, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 284', 657.71, 164, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 225', 2155.58, 251, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 735', 2342.29, 200, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 477', 3350.29, 241, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 518', 2630.54, 48, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 569', 2091.49, 146, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 231', 3879.31, 63, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 404', 3185.67, 124, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 804', 857.09, 280, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 159', 2066.05, 24, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 284', 1437.51, 228, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 913', 397.73, 60, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 647', 4440.72, 99, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 315', 1512.46, 186, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 344', 1020.16, 37, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 739', 2520.37, 147, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 390', 1849.66, 56, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 254', 826.93, 222, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 462', 4149.09, 87, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 365', 1153.58, 102, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 845', 3880.33, 18, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 108', 3431.91, 34, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 356', 3801.24, 160, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 202', 363.95, 258, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 611', 1377.01, 112, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 637', 3870.5, 18, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 180', 4720.64, 20, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 794', 4874.36, 296, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 154', 1513.11, 121, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 745', 234.39, 17, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 389', 3388.89, 111, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 762', 4783.59, 298, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 953', 223.19, 272, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 138', 4689.25, 284, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 309', 1950.28, 14, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 922', 3570.82, 287, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 588', 1853.39, 269, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 414', 405.0, 45, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 498', 3647.06, 129, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 880', 221.46, 250, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 640', 4342.83, 80, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 982', 4707.18, 44, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 105', 1819.31, 228, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 577', 4972.06, 20, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 426', 2677.74, 95, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 828', 2726.73, 257, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 236', 3712.17, 278, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 489', 4734.91, 128, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 687', 2992.8, 212, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 790', 1902.83, 156, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 551', 3866.18, 217, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 382', 3287.61, 34, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 675', 2435.75, 30, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 678', 176.2, 129, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 764', 2400.19, 189, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 351', 3445.53, 234, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 346', 1553.02, 71, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 286', 2445.57, 121, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 489', 2459.1, 91, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 571', 1130.64, 47, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 705', 2539.86, 198, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 999', 2277.5, 66, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 820', 383.96, 53, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 473', 2071.96, 122, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 760', 3540.51, 151, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 254', 1932.07, 187, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 166', 2417.83, 233, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 660', 2363.26, 275, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 242', 3505.56, 156, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 881', 3702.72, 14, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 639', 189.9, 143, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 445', 1677.86, 282, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 711', 4871.82, 133, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 391', 4708.12, 34, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 533', 1441.92, 93, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 753', 1324.99, 289, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 191', 3809.3, 123, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 293', 4670.11, 238, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 683', 805.02, 51, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 785', 554.36, 79, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 541', 1279.91, 271, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 319', 2603.68, 59, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 873', 2515.76, 163, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 230', 4487.14, 117, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('SSD Modelo 613', 3343.6, 169, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 540', 3379.49, 180, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 123', 4227.89, 237, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 609', 1882.88, 276, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 341', 4531.75, 184, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 611', 2560.25, 163, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 817', 3393.79, 67, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 252', 2855.2, 123, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 272', 488.89, 190, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 428', 3623.11, 127, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 515', 4853.47, 87, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 603', 3747.32, 271, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 804', 361.98, 67, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 614', 1637.81, 5, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 316', 4353.5, 197, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 960', 1153.28, 282, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 399', 3720.8, 25, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 890', 2320.14, 206, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 409', 2099.07, 72, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 650', 184.75, 223, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Teclado Modelo 878', 2689.94, 198, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 456', 4627.17, 288, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 737', 839.21, 140, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 362', 1802.72, 273, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 782', 3422.3, 80, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 600', 4726.69, 149, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Pendrive Modelo 748', 1854.35, 221, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 230', 458.88, 259, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 631', 3930.58, 41, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 127', 2220.48, 71, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 874', 4442.6, 62, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 768', 2716.49, 96, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 347', 1721.54, 296, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 216', 3036.16, 219, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 300', 1188.92, 11, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Webcam Modelo 403', 2643.7, 46, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 248', 1312.89, 298, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Mouse Modelo 295', 2615.66, 22, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 389', 969.61, 227, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 735', 1838.52, 157, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 411', 2860.47, 86, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Caixa de Som Modelo 499', 2447.21, 31, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 942', 2518.99, 36, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('HD Externo Modelo 489', 499.93, 56, 'Max Eletrônicos');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 934', 2687.01, 267, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Impressora Modelo 783', 2172.36, 116, 'Mega Store');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 779', 4361.74, 262, 'InfoSul');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 499', 1340.03, 89, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Notebook Modelo 705', 4281.97, 126, 'GlobalTech');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 228', 1556.01, 63, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 619', 623.88, 212, 'Tech Distribuidora');
INSERT INTO produtos (nome, preco, quantidade, fornecedor) VALUES ('Monitor Modelo 130', 3783.76, 138, 'Max Eletrônicos');
